'use client';

import React, { useCallback, useEffect, useRef, useState } from 'react';
import Markdown from './Markdown';
import UserSelector from './UserSelector';
import RepoInfo from '@/types/repoinfo';
import getRepoUrl from '@/utils/getRepoUrl';
import { createChatWebSocket, closeWebSocket, ChatCompletionRequest } from '@/utils/websocketClient';
import { WikiPage } from '@/types/wiki/wikipage';

// Char budget for wiki content embedded in the review prompt (~20k tokens),
// sized so smaller reviewer models (e.g. 32k-context vLLM) still fit the
// request. Pages are truncated proportionally AND the total is hard-capped.
const MAX_REVIEW_CHARS = 80_000;

interface WikiReview {
  repo: RepoInfo;
  language: string;
  reviewed_provider: string;
  reviewed_model: string;
  reviewer_provider: string;
  reviewer_model: string;
  content: string;
  created_at?: string;
}

interface WikiReviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  repoInfo: RepoInfo;
  language: string;
  pages: WikiPage[];          // pages of the currently loaded wiki version
  reviewedProvider: string;   // provider/model that generated the loaded wiki
  reviewedModel: string;
  token?: string;
}

export default function WikiReviewModal({
  isOpen,
  onClose,
  repoInfo,
  language,
  pages,
  reviewedProvider,
  reviewedModel,
  token,
}: WikiReviewModalProps) {
  const [reviewerProvider, setReviewerProvider] = useState('');
  const [reviewerModel, setReviewerModel] = useState('');
  const [isCustomModel, setIsCustomModel] = useState(false);
  const [customModel, setCustomModel] = useState('');
  const [reviewContent, setReviewContent] = useState('');
  const [isReviewing, setIsReviewing] = useState(false);
  const [reviewError, setReviewError] = useState<string | null>(null);
  const [pastReviews, setPastReviews] = useState<WikiReview[]>([]);
  const webSocketRef = useRef<WebSocket | null>(null);
  const abortedRef = useRef(false);

  // Load past reviews whenever the modal opens
  useEffect(() => {
    if (!isOpen) return;
    const params = new URLSearchParams({
      owner: repoInfo.owner,
      repo: repoInfo.repo,
      repo_type: repoInfo.type,
      language: language,
    });
    fetch(`/api/wiki_review?${params.toString()}`)
      .then(res => (res.ok ? res.json() : []))
      .then((data: WikiReview[]) => setPastReviews(Array.isArray(data) ? data : []))
      .catch(() => setPastReviews([]));
  }, [isOpen, repoInfo.owner, repoInfo.repo, repoInfo.type, language]);

  // Close any in-flight websocket on unmount
  useEffect(() => () => closeWebSocket(webSocketRef.current), []);

  // Stop any in-flight review when the modal is closed (component stays mounted).
  useEffect(() => {
    if (!isOpen && webSocketRef.current) {
      abortedRef.current = true; // suppress the save in the onClose handler
      closeWebSocket(webSocketRef.current);
      webSocketRef.current = null;
      setIsReviewing(false);
    }
  }, [isOpen]);

  // Short retrieval query so the backend can fetch code context via RAG even
  // though the full review prompt exceeds the websocket's large-input gate.
  const buildRagQuery = useCallback(() => {
    const titles = pages.map(p => p.title).join('; ').slice(0, 1000);
    const files = [...new Set(pages.flatMap(p => p.filePaths))].slice(0, 50).join(', ');
    return `Source code relevant to documentation covering: ${titles}. Key files: ${files}`.slice(0, 4000);
  }, [pages]);

  const buildReviewPrompt = useCallback(() => {
    const perPageBudget = Math.max(2000, Math.floor(MAX_REVIEW_CHARS / Math.max(pages.length, 1)));
    let wikiText = pages.map(page => {
      const body = page.content.length > perPageBudget
        ? page.content.slice(0, perPageBudget) + '\n\n...[truncated for review]'
        : page.content;
      return `<page title="${page.title}" files="${page.filePaths.join(', ')}">\n${body}\n</page>`;
    }).join('\n\n');
    if (wikiText.length > MAX_REVIEW_CHARS) {
      // Hard cap: per-page minimums can overshoot on wikis with many pages
      wikiText = wikiText.slice(0, MAX_REVIEW_CHARS) + '\n\n...[wiki truncated for review]';
    }
    return `You are reviewing AI-generated wiki documentation for the repository ${getRepoUrl(repoInfo)}.
The wiki below was generated by ${reviewedProvider}/${reviewedModel}. You have access to the repository's actual source code through the provided context — use it to verify claims.

Review the wiki for:
1. Factual accuracy against the actual code (wrong claims, invented APIs, incorrect architecture descriptions)
2. Completeness (important modules, flows or configuration that are missing or under-explained)
3. Clarity and structure
4. Mermaid diagram correctness

Be specific: name the page and quote the inaccurate statement when you flag something. End with a short summary verdict and an overall quality score from 1-10.

<wiki>
${wikiText}
</wiki>`;
  }, [pages, repoInfo, reviewedProvider, reviewedModel]);

  const saveReview = useCallback(async (content: string, provider: string, model: string) => {
    try {
      const response = await fetch('/api/wiki_review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          // Never persist access tokens — strip before sending to the backend.
          repo: { ...repoInfo, token: null },
          language: language,
          reviewed_provider: reviewedProvider,
          reviewed_model: reviewedModel,
          reviewer_provider: provider,
          reviewer_model: model,
          content: content,
        }),
      });
      if (response.ok) {
        const saved = await response.json().catch(() => null);
        setPastReviews(prev => [{
          repo: repoInfo,
          language,
          reviewed_provider: reviewedProvider,
          reviewed_model: reviewedModel,
          reviewer_provider: provider,
          reviewer_model: model,
          content,
          created_at: saved?.created_at,
        }, ...prev.filter(r =>
          !(r.reviewed_provider === reviewedProvider && r.reviewed_model === reviewedModel &&
            r.reviewer_provider === provider && r.reviewer_model === model))]);
      } else {
        console.error('Failed to save wiki review:', response.status, await response.text());
      }
    } catch (err) {
      console.error('Error saving wiki review:', err);
    }
  }, [repoInfo, language, reviewedProvider, reviewedModel]);

  const startReview = useCallback(() => {
    const effectiveModel = isCustomModel ? customModel : reviewerModel;
    if (!reviewerProvider || !effectiveModel) {
      setReviewError('Select a reviewer provider and model first.');
      return;
    }
    closeWebSocket(webSocketRef.current);
    setReviewError(null);
    setReviewContent('');
    setIsReviewing(true);
    abortedRef.current = false;

    const request: ChatCompletionRequest = {
      repo_url: getRepoUrl(repoInfo),
      type: repoInfo.type,
      messages: [{ role: 'user', content: buildReviewPrompt() }],
      provider: reviewerProvider,
      model: effectiveModel,
      language: language,
      token: token,
      rag_query: buildRagQuery(),
    };

    let content = '';
    webSocketRef.current = createChatWebSocket(
      request,
      (message: string) => {
        content += message;
        setReviewContent(content);
      },
      () => {
        setIsReviewing(false);
        setReviewError('Error during review generation. Check the reviewer model and try again.');
      },
      () => {
        setIsReviewing(false);
        if (abortedRef.current) {
          return; // user closed the modal mid-stream — discard, don't save
        }
        const finished = content.trim();
        if (finished && !finished.startsWith('Error:')) {
          saveReview(content, reviewerProvider, effectiveModel);
        } else if (finished) {
          // Backend reported a failure as message text — surface it, don't save it.
          setReviewError(finished.slice(0, 300));
        }
      },
    );
  }, [reviewerProvider, reviewerModel, isCustomModel, customModel, repoInfo, language, token, buildReviewPrompt, buildRagQuery, saveReview]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div className="flex min-h-screen items-center justify-center p-4 text-center bg-black/50">
        <div className="relative transform overflow-hidden rounded-lg bg-[var(--card-bg)] text-left shadow-xl transition-all sm:my-8 sm:max-w-3xl sm:w-full">
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border-color)]">
            <h3 className="text-lg font-medium text-[var(--accent-primary)]">
              Model Review — wiki by {reviewedProvider}/{reviewedModel}
            </h3>
            <button
              type="button"
              onClick={onClose}
              className="text-[var(--muted)] hover:text-[var(--foreground)] focus:outline-none transition-colors"
            >
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Body */}
          <div className="p-6 max-h-[70vh] overflow-y-auto">
            <p className="text-sm text-[var(--muted)] mb-4">
              Pick a different model to review this wiki against the repository&apos;s actual code.
            </p>
            <UserSelector
              provider={reviewerProvider}
              setProvider={setReviewerProvider}
              model={reviewerModel}
              setModel={setReviewerModel}
              isCustomModel={isCustomModel}
              setIsCustomModel={setIsCustomModel}
              customModel={customModel}
              setCustomModel={setCustomModel}
              showFileFilters={false}
            />

            {reviewError && (
              <div className="mt-4 p-3 rounded-md border border-[var(--highlight)]/30 text-sm text-[var(--highlight)]">
                {reviewError}
              </div>
            )}

            {reviewContent && (
              <div className="mt-4 p-4 rounded-md border border-[var(--border-color)] bg-[var(--background)]">
                <Markdown content={reviewContent} />
              </div>
            )}

            {/* Past reviews */}
            {pastReviews.length > 0 && !reviewContent && (
              <div className="mt-6">
                <h4 className="text-sm font-medium text-[var(--foreground)] mb-2">Saved reviews</h4>
                <div className="space-y-2">
                  {pastReviews.map((review) => (
                    <button
                      key={`${review.reviewed_provider}~${review.reviewed_model}~${review.reviewer_provider}~${review.reviewer_model}`}
                      type="button"
                      onClick={() => setReviewContent(review.content)}
                      className="block w-full text-left p-3 rounded-md border border-[var(--border-color)] hover:bg-[var(--background)] transition-colors"
                    >
                      <span className="text-sm text-[var(--foreground)]">
                        {review.reviewed_provider}/{review.reviewed_model} reviewed by {review.reviewer_provider}/{review.reviewer_model}
                      </span>
                      {review.created_at && (
                        <span className="block text-xs text-[var(--muted)] mt-1">
                          {new Date(review.created_at).toLocaleString()}
                        </span>
                      )}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-end gap-2 px-6 py-4 border-t border-[var(--border-color)]">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium rounded-md border border-[var(--border-color)]/50 text-[var(--muted)] bg-transparent hover:bg-[var(--background)] hover:text-[var(--foreground)] transition-colors"
            >
              Close
            </button>
            <button
              type="button"
              onClick={startReview}
              disabled={isReviewing || pages.length === 0}
              className="px-4 py-2 text-sm font-medium rounded-md border border-transparent bg-[var(--accent-primary)]/90 text-white hover:bg-[var(--accent-primary)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {isReviewing ? 'Reviewing…' : 'Start Review'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
