"""Tests for per-model wiki cache versioning (api/api.py)."""
import asyncio
import json
import os

import pytest
from fastapi import HTTPException

import api.api as api_module
from api.api import (
    RepoInfo,
    WikiCacheRequest,
    WikiPage,
    WikiStructureModel,
    get_wiki_cache_path,
    list_wiki_cache_paths,
    parse_wiki_cache_filename,
    read_wiki_cache,
    sanitize_version_segment,
    save_wiki_cache,
)


@pytest.fixture
def cache_dir(tmp_path, monkeypatch):
    """Point the module-level cache dir at a temp dir."""
    monkeypatch.setattr(api_module, "WIKI_CACHE_DIR", str(tmp_path))
    return tmp_path


def make_cache_request(provider="claude", model="claude-sonnet-4-6"):
    page = WikiPage(
        id="p1",
        title="Page 1",
        content=f"# Generated by {provider}/{model}",
        filePaths=["a.py"],
        importance="high",
        relatedPages=[],
    )
    structure = WikiStructureModel(
        id="wiki", title="Wiki", description="d", pages=[page]
    )
    return WikiCacheRequest(
        repo=RepoInfo(owner="owner", repo="repo", type="github"),
        language="en",
        wiki_structure=structure,
        generated_pages={"p1": page},
        provider=provider,
        model=model,
    )


# --- sanitize_version_segment ---

def test_sanitize_passthrough():
    assert sanitize_version_segment("claude-sonnet-4-6") == "claude-sonnet-4-6"

def test_sanitize_replaces_slash():
    assert sanitize_version_segment("Qwen/Qwen3-32B") == "Qwen-Qwen3-32B"

def test_sanitize_is_idempotent():
    once = sanitize_version_segment("Qwen/Qwen3-32B")
    assert sanitize_version_segment(once) == once

def test_sanitize_empty_and_none():
    assert sanitize_version_segment("") == ""
    assert sanitize_version_segment(None) == ""
    assert sanitize_version_segment("///") == ""


# --- get_wiki_cache_path ---

def test_path_without_version_is_legacy(cache_dir):
    path = get_wiki_cache_path("owner", "repo", "github", "en")
    assert os.path.basename(path) == "deepwiki_cache_github_owner_repo_en.json"

def test_path_with_version_has_tilde_suffix(cache_dir):
    path = get_wiki_cache_path("owner", "repo", "github", "en",
                               provider="claude", model="claude-sonnet-4-6")
    assert os.path.basename(path) == (
        "deepwiki_cache_github_owner_repo_en~claude~claude-sonnet-4-6.json"
    )

def test_path_sanitizes_model_slash(cache_dir):
    path = get_wiki_cache_path("owner", "repo", "github", "en",
                               provider="vllm", model="Qwen/Qwen3-32B")
    assert os.path.basename(path) == (
        "deepwiki_cache_github_owner_repo_en~vllm~Qwen-Qwen3-32B.json"
    )

def test_path_partial_version_falls_back_to_legacy(cache_dir):
    path = get_wiki_cache_path("owner", "repo", "github", "en",
                               provider="claude", model=None)
    assert os.path.basename(path) == "deepwiki_cache_github_owner_repo_en.json"

def test_path_rejects_bad_owner(cache_dir):
    with pytest.raises(HTTPException):
        get_wiki_cache_path("../evil", "repo", "github", "en",
                            provider="claude", model="m")


# --- parse_wiki_cache_filename ---

def test_parse_legacy_filename():
    parsed = parse_wiki_cache_filename(
        "deepwiki_cache_github_AsyncFuncAI_deepwiki-open_en.json")
    assert parsed == {
        "repo_type": "github", "owner": "AsyncFuncAI",
        "repo": "deepwiki-open", "language": "en",
        "provider": None, "model": None,
    }

def test_parse_versioned_filename_with_underscored_repo():
    parsed = parse_wiki_cache_filename(
        "deepwiki_cache_github_owner_my_repo_en~claude~claude-sonnet-4-6.json")
    assert parsed == {
        "repo_type": "github", "owner": "owner",
        "repo": "my_repo", "language": "en",
        "provider": "claude", "model": "claude-sonnet-4-6",
    }

def test_parse_rejects_non_cache_files():
    assert parse_wiki_cache_filename("notacache.json") is None
    assert parse_wiki_cache_filename("deepwiki_cache_github_owner.json") is None


# --- save/read roundtrip & newest-wins (functions added in Task 2) ---

def _set_mtime(path, ts):
    os.utime(path, (ts, ts))

def test_save_creates_version_file_and_reads_back(cache_dir):
    req = make_cache_request("claude", "claude-sonnet-4-6")
    assert asyncio.run(save_wiki_cache(req)) is True
    expected = cache_dir / "deepwiki_cache_github_owner_repo_en~claude~claude-sonnet-4-6.json"
    assert expected.exists()

    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en",
                                       provider="claude", model="claude-sonnet-4-6"))
    assert data is not None
    assert data.provider == "claude"
    assert data.generated_pages["p1"].content == "# Generated by claude/claude-sonnet-4-6"

def test_two_models_do_not_overwrite(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    asyncio.run(save_wiki_cache(make_cache_request("vllm", "Qwen/Qwen3-32B")))
    files = [f for f in os.listdir(cache_dir) if f.endswith(".json")]
    assert len(files) == 2

def test_read_without_version_returns_newest(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    asyncio.run(save_wiki_cache(make_cache_request("vllm", "Qwen/Qwen3-32B")))
    claude_file = cache_dir / "deepwiki_cache_github_owner_repo_en~claude~claude-sonnet-4-6.json"
    vllm_file = cache_dir / "deepwiki_cache_github_owner_repo_en~vllm~Qwen-Qwen3-32B.json"
    _set_mtime(str(claude_file), 1_000_000)
    _set_mtime(str(vllm_file), 2_000_000)

    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en"))
    assert data.provider == "vllm"

    # Flip mtimes -> the other version is newest now
    _set_mtime(str(claude_file), 3_000_000)
    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en"))
    assert data.provider == "claude"

def test_read_falls_back_to_legacy_file(cache_dir):
    legacy = cache_dir / "deepwiki_cache_github_owner_repo_en.json"
    req = make_cache_request("google", "gemini-2.0-flash")
    payload = {
        "wiki_structure": req.wiki_structure.model_dump(),
        "generated_pages": {k: v.model_dump() for k, v in req.generated_pages.items()},
        "provider": "google",
        "model": "gemini-2.0-flash",
    }
    legacy.write_text(json.dumps(payload), encoding="utf-8")

    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en"))
    assert data is not None
    assert data.provider == "google"

def test_read_exact_version_miss_returns_none(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en",
                                       provider="openai", model="gpt-4o"))
    assert data is None

def test_read_skips_corrupt_newest_file(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    corrupt = cache_dir / "deepwiki_cache_github_owner_repo_en~vllm~broken.json"
    corrupt.write_text("{not valid json", encoding="utf-8")
    claude_file = cache_dir / "deepwiki_cache_github_owner_repo_en~claude~claude-sonnet-4-6.json"
    _set_mtime(str(claude_file), 1_000_000)
    _set_mtime(str(corrupt), 2_000_000)

    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en"))
    assert data is not None
    assert data.provider == "claude"

def test_list_wiki_cache_paths_only_matches_this_repo(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    other = cache_dir / "deepwiki_cache_github_owner_repo2_en~claude~m.json"
    other.write_text("{}", encoding="utf-8")
    paths = list_wiki_cache_paths("owner", "repo", "github", "en")
    assert len(paths) == 1
    assert "repo2" not in paths[0]


# --- DELETE endpoint (Task 3) ---

def test_delete_specific_version_only(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    asyncio.run(save_wiki_cache(make_cache_request("vllm", "Qwen/Qwen3-32B")))

    result = asyncio.run(api_module.delete_wiki_cache(
        owner="owner", repo="repo", repo_type="github", language="en",
        provider="claude", model="claude-sonnet-4-6", authorization_code=None))
    assert "deleted" in result

    remaining = [f for f in os.listdir(cache_dir) if f.endswith(".json")]
    assert remaining == ["deepwiki_cache_github_owner_repo_en~vllm~Qwen-Qwen3-32B.json"]

def test_delete_without_version_removes_all(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    asyncio.run(save_wiki_cache(make_cache_request("vllm", "Qwen/Qwen3-32B")))
    (cache_dir / "deepwiki_cache_github_owner_repo_en.json").write_text("{}", encoding="utf-8")

    asyncio.run(api_module.delete_wiki_cache(
        owner="owner", repo="repo", repo_type="github", language="en",
        provider=None, model=None, authorization_code=None))
    assert [f for f in os.listdir(cache_dir) if f.endswith(".json")] == []

def test_delete_missing_version_raises_404(cache_dir):
    with pytest.raises(HTTPException) as exc:
        asyncio.run(api_module.delete_wiki_cache(
            owner="owner", repo="repo", repo_type="github", language="en",
            provider="openai", model="gpt-4o", authorization_code=None))
    assert exc.value.status_code == 404


# --- generation metadata & export format ---

def test_save_sets_generated_at(cache_dir):
    asyncio.run(save_wiki_cache(make_cache_request("claude", "claude-sonnet-4-6")))
    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en",
                                       provider="claude", model="claude-sonnet-4-6"))
    assert data.generated_at  # ISO timestamp set server-side on save
    assert "T" in data.generated_at

def test_get_repo_commit_missing_repo_returns_none():
    commit = api_module.get_repo_commit(
        RepoInfo(owner="definitely-not", repo="cloned", type="github"))
    assert commit is None

def test_get_repo_commit_reads_head_of_local_repo(tmp_path):
    import subprocess
    subprocess.run(["git", "init"], cwd=tmp_path, check=True, capture_output=True)
    (tmp_path / "f.txt").write_text("x")
    subprocess.run(["git", "add", "."], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "-c", "user.email=t@t.t", "-c", "user.name=t",
                    "commit", "-m", "init"], cwd=tmp_path, check=True, capture_output=True)
    commit = api_module.get_repo_commit(
        RepoInfo(owner="o", repo="r", type="local", localPath=str(tmp_path)))
    assert commit is not None and len(commit) == 40

def test_markdown_export_includes_generation_metadata():
    req = make_cache_request("claude", "claude-sonnet-4-6")
    md = api_module.generate_markdown_export(
        "https://github.com/owner/repo", list(req.generated_pages.values()),
        provider="claude", model="claude-sonnet-4-6",
        generated_at="2026-06-05T00:00:00+00:00", repo_commit="abc1234")
    assert "claude/claude-sonnet-4-6" in md
    assert "abc1234" in md
    assert "2026-06-05T00:00:00+00:00" in md

def test_json_export_includes_generation_metadata():
    req = make_cache_request("claude", "claude-sonnet-4-6")
    out = json.loads(api_module.generate_json_export(
        "https://github.com/owner/repo", list(req.generated_pages.values()),
        provider="claude", model="claude-sonnet-4-6",
        generated_at="2026-06-05T00:00:00+00:00", repo_commit="abc1234"))
    assert out["metadata"]["provider"] == "claude"
    assert out["metadata"]["model"] == "claude-sonnet-4-6"
    assert out["metadata"]["repo_commit"] == "abc1234"
    assert out["metadata"]["generated_at"] == "2026-06-05T00:00:00+00:00"


# --- cross-model wiki reviews ---

def make_review(reviewer_provider="openai", reviewer_model="gpt-4o", content="Looks accurate."):
    return api_module.WikiReviewData(
        repo=RepoInfo(owner="owner", repo="repo", type="github"),
        language="en",
        reviewed_provider="claude",
        reviewed_model="claude-sonnet-4-6",
        reviewer_provider=reviewer_provider,
        reviewer_model=reviewer_model,
        content=content,
    )

def test_review_save_and_list_roundtrip(cache_dir):
    asyncio.run(api_module.store_wiki_review(make_review()))
    reviews = asyncio.run(api_module.get_wiki_reviews(
        owner="owner", repo="repo", repo_type="github", language="en"))
    assert len(reviews) == 1
    assert reviews[0].reviewer_provider == "openai"
    assert reviews[0].reviewed_model == "claude-sonnet-4-6"
    assert reviews[0].created_at  # set server-side

def test_review_same_key_overwrites(cache_dir):
    asyncio.run(api_module.store_wiki_review(make_review(content="v1")))
    asyncio.run(api_module.store_wiki_review(make_review(content="v2")))
    reviews = asyncio.run(api_module.get_wiki_reviews(
        owner="owner", repo="repo", repo_type="github", language="en"))
    assert len(reviews) == 1
    assert reviews[0].content == "v2"

def test_review_different_reviewers_coexist(cache_dir):
    asyncio.run(api_module.store_wiki_review(make_review("openai", "gpt-4o")))
    asyncio.run(api_module.store_wiki_review(make_review("vllm", "Qwen/Qwen3-32B")))
    reviews = asyncio.run(api_module.get_wiki_reviews(
        owner="owner", repo="repo", repo_type="github", language="en"))
    assert len(reviews) == 2

def test_review_files_invisible_to_wiki_cache(cache_dir):
    asyncio.run(api_module.store_wiki_review(make_review()))
    review_files = os.listdir(cache_dir)
    assert len(review_files) == 1
    assert review_files[0].startswith("deepwiki_review_")
    # Review files are not parsed as wiki caches and not picked up by newest-wins
    assert parse_wiki_cache_filename(review_files[0]) is None
    assert list_wiki_cache_paths("owner", "repo", "github", "en") == []


def test_review_save_strips_repo_token(cache_dir):
    review = make_review()
    review.repo.token = "ghp_secret"
    asyncio.run(api_module.store_wiki_review(review))
    reviews = asyncio.run(api_module.get_wiki_reviews(
        owner="owner", repo="repo", repo_type="github", language="en"))
    assert reviews[0].repo.token is None


def test_cache_save_strips_repo_token(cache_dir):
    req = make_cache_request("claude", "claude-sonnet-4-6")
    req.repo.token = "ghp_secret"
    asyncio.run(save_wiki_cache(req))
    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en",
                                       provider="claude", model="claude-sonnet-4-6"))
    assert data.repo.token is None


def test_read_strips_token_from_legacy_files(cache_dir):
    """Files written before the save-path strip may still carry tokens."""
    req = make_cache_request("claude", "claude-sonnet-4-6")
    payload = {
        "wiki_structure": req.wiki_structure.model_dump(),
        "generated_pages": {k: v.model_dump() for k, v in req.generated_pages.items()},
        "repo": {"owner": "owner", "repo": "repo", "type": "github", "token": "ghp_secret"},
        "provider": "claude",
        "model": "claude-sonnet-4-6",
    }
    f = cache_dir / "deepwiki_cache_github_owner_repo_en~claude~claude-sonnet-4-6.json"
    f.write_text(json.dumps(payload), encoding="utf-8")
    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en",
                                       provider="claude", model="claude-sonnet-4-6"))
    assert data.repo.token is None


def test_self_reviewed_flag_roundtrip(cache_dir):
    req = make_cache_request("claude", "claude-sonnet-4-6")
    req.self_reviewed = True
    asyncio.run(save_wiki_cache(req))
    data = asyncio.run(read_wiki_cache("owner", "repo", "github", "en",
                                       provider="claude", model="claude-sonnet-4-6"))
    assert data.self_reviewed is True
